<?php
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link https://github.com/pacificnm/pacificnm-controller for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license https://github.com/pacificnm/pacificnm-controller/blob/master/LICENSE.md
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
                    <i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate($this->layout()->pageTitle); ?> 
					<small><?php echo $this->translate("New"); ?></small>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
                <?php echo $this->form()->openTag($this->form); ?>
                
				<?php echo $this->partial("partials/form-errors.phtml", array("errorMsg" => $this->form->getMessages())); ?>
		
				<div class="row">
              		<div class="col-xs-12">
              			<?php echo $this->formElementDisplay($this->form->get("controllerName")); ?>
					</div>
              	</div>
		
				<div class="row">
              		<div class="col-xs-12">
              			<?php echo $this->formElementDisplay($this->form->get("moduleId")); ?>
					</div>
              	</div>
              	
                <div class="row">
					<div class="col-xs-12">
						<?php echo $this->formElementDisplay($this->form->get("submit")); ?>
					</div>
				</div>
				
				<?php echo $this->formElementDisplay($this->form->get("controllerId")); ?>
				
				<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>